# Copyright (c) 2019 Cloudware S.A. - All rights reserved.

source 'https://rubygems.org'

gem 'awesome_print'
gem 'colorize'
gem 'rake-compiler'

group :development do
  gem 'pry'
  gem 'ruby-debug'
end
