require 'sp/jsonapi/model/concerns/model'

module SP
  module JSONAPI
    module Model

      class Base
        include SP::JSONAPI::Model::Concerns::Model

        @@adapter = nil
        @@include_root_in_json = true

        def self.adapter ; @@adapter ; end
        def self.adapter=(value) ; @@adapter = value ; end

        def self.include_root_in_json ; @@include_root_in_json ; end
        def self.include_root_in_json=(value) ; @@include_root_in_json = value ; end

        def self.inherited(child)
          child.resource_name = child.name.demodulize.underscore.pluralize
          child.autogenerated_id = true
        end

        def self.i18n_scope
          :activerecord
        end
      end

    end
  end
end
